### ISSUE TITLE
Ich habe Probleme - Dateien fehlern

### ISSUE THREAD

**Issue by IGLO70** [spitzlbergerj/CaravanPi#2]
laut Installationsanleitung
pm2 start /home/pi/CaravanPi/pm2/ecosystem.caravanpi.js
aber 
[PM2][ERROR] Script not found: /home/pi/CaravanPi/pm2/ecosystem.caravanpi.js

den Ordner pm2 gibt es gar nicht.

Ich finde das ist ein tolles Projekt, bin aber kein "Programmierer", so das ich nur die Anleitung Schritt für Schritt abarbeiten kann. Jetzt weiß ich leider nicht mehr weiter.

Als ersten Schritt möchte ich eigentlich nur die "Wasserwaage" und die Raum- Aussentemperatur aktivieren.

**Comment by spitzlbergerj** [comment]
Hallo @IGLO70,

Zum ersten, das Projekt ist "work in progress" - im Moment sogar geparkt, weil ich aktuell keine Zeit zur weiterarbeiten finde. 

Wo steht den der von dir angegebene installationshinweis? 

Viele Grüße 
Sepp

**Comment by spitzlbergerj** [comment]
Noch eine frage: Hast du auf dem Raspberry den magic mirror installiert? Der liefert pm2 mit. Ohne magic mirror funktioniert der automatische Start über pm2 nicht. Dann müsstest du alles über eine crontab steuern

**Comment by spitzlbergerj** [comment]
So steht das auch im Kapitel Installing pm2 and crontabs

**Comment by IGLO70** [comment]
MagicMirror ist installiert und läuft auch einwandfrei. Ich kenne mich nur beim Raspberry zu wenig aus, um die *.py Scripte, zum auslesen der Sensorik richtig aufzurufen und zu starten. Die Anzeige des Wohnwagens und der Temperaturanzeigen habe ich geschaft, aber keine Werte. 
Aber durch Covid19 habe auch ich mit meinem Projekt keinen Zeitdruck. Mein nächster Urlaub ist auf  xxx Zeit verschoben.

Nochmals Gratulation, ein tolles Projekt

Grüße aus der Steiermark

Ignaz

**Comment by spitzlbergerj** [comment]
Hallo Ignaz,

Dann gib mir etwas Zeit. Ich habe das Projekt gerade eingemottet und muss den raspberry erst wieder auspacken. Vielleicht klappt es bis nächstes Wochenende.

**Comment by spitzlbergerj** [comment]
Hallo Ignaz,
ich habe das Directory .../CaravanPi/pm2 nun auf github eingespielt. Ich konnte den Start aber nicht mehr testen. 
Auf meinem Pi, von dem ich die  Dateien geholt habe, läuft pm2 und position2file.py wird vom pm2 überwacht. Ich habe aber keine weiteren Aufzeichnungen zum Einrichten des pm2 gefunden außer die im Wiki.
Magst du es einfach mal probieren bitte, ob das so schon funktioniert?
Falls pm2 sich nicht wie im Wiki starten lässt, dann muss ich noch weiter suchen.
Viele Grüße
Sepp

**Comment by IGLO70** [comment]
Danke für die Dateien.

 

Ich habe das Projekt jetzt soweit auf einem Steckbrett aufgebaut, um den Lagesensor zu testen, und dabei habe ich so meine Probleme.

 

1.	Problem

 



 

Das Programm i2cdetect zeigt mir an, das der Sensor an der richtigen Adresse erkannt wird.

Im Programm werden Lagedaten aber nur manchmal, nach einem Neustart des Raspberry einmalig eingelesen. Zu 99% zeigt mir

PM2 log immer nur folgenden Meldung:

.

Da ich in Python und Java noch nie gearbeitet habe, weis ich nicht, wo ich hier weitersuchen soll.

Einen Fehler des Lagesensors kann ich ausschließen, denn an einem ESP32 angeschlossen liefert er kontinuierlich aktuelle Werte.

 

2.	Problem

Die Klimasensoren habe ich nicht direkt am Pi angeschlossen, sondern die Werte werden mit einem ESP32 erfasst und über Wlan und ein PHP Script in die Dateien für die aktuellen Messwerte geschrieben.

Die Dateien  haben die vorgegebene Struktur und werden auch jede Minute mit einem neuen Messwert erweitert.

Hier finde ich im MM Error log dann immer folgende Einträge:



Die aktuellen Dateien mit meinen Messwerten vom Testaufbau sind im Anhang.

 

Die Taster zum Einschalten, Kalibrieren usw. habe ich noch nicht angeschlossen, den dann bekomme ich den Raspberry nicht mehr in Betrieb, sondern er geht in eine Endlosschleife von Start – Ausschalten – Start – Ausschalten. Sobald nach Erscheinen des Desktop der MM Starten soll, wird er der Raspberry wieder heruntergefahren und starten danach neu. 

Vielleicht können Sie die Daten einmal kurz kontrollieren und haben eine Idee woran ich momentan scheitere.

 

Mit besten Dank

 

Ignaz Lorenz

 

 

Von: Josef Spitzlberger <notifications@github.com> 
Gesendet: Mittwoch, 1. April 2020 06:40
An: spitzlbergerj/CaravanPi <CaravanPi@noreply.github.com>
Cc: IGLO70 <ignaz.lorenz@gmail.com>; Mention <mention@noreply.github.com>
Betreff: Re: [spitzlbergerj/CaravanPi] Ich habe Probleme - Dateien fehlern (#2)

 

Hallo Ignaz,
ich habe das Directory .../CaravanPi/pm2 nun auf github eingespielt. Ich konnte den Start aber nicht mehr testen.
Auf meinem Pi, von dem ich die Dateien geholt habe, läuft pm2 und position2file.py wird vom pm2 überwacht. Ich habe aber keine weiteren Aufzeichnungen zum Einrichten des pm2 gefunden außer die im Wiki.
Magst du es einfach mal probieren bitte, ob das so schon funktioniert?
Falls pm2 sich nicht wie im Wiki starten lässt, dann muss ich noch weiter suchen.
Viele Grüße
Sepp

**Comment by IGLO70** [comment]
Noch ein Nachtrag, manchmal kommt auch dieser Eintrag in den Logdateien vom MM:



 

Ich bin momentan hilflos, was diese Meldungen bedeuten.

 

Ignaz Lorenz

 

Von: Josef Spitzlberger <notifications@github.com> 
Gesendet: Mittwoch, 1. April 2020 06:40
An: spitzlbergerj/CaravanPi <CaravanPi@noreply.github.com>
Cc: IGLO70 <ignaz.lorenz@gmail.com>; Mention <mention@noreply.github.com>
Betreff: Re: [spitzlbergerj/CaravanPi] Ich habe Probleme - Dateien fehlern (#2)

 

Hallo Ignaz,
ich habe das Directory .../CaravanPi/pm2 nun auf github eingespielt. Ich konnte den Start aber nicht mehr testen.
Auf meinem Pi, von dem ich die Dateien geholt habe, läuft pm2 und position2file.py wird vom pm2 überwacht. Ich habe aber keine weiteren Aufzeichnungen zum Einrichten des pm2 gefunden außer die im Wiki.
Magst du es einfach mal probieren bitte, ob das so schon funktioniert?
Falls pm2 sich nicht wie im Wiki starten lässt, dann muss ich noch weiter suchen.
Viele Grüße
Sepp

**Comment by spitzlbergerj** [comment]
Hallo Ignaz,
ich kann hier die Meldungstexte nicht sehen. Daher tu ich mich schwer mit der Fehleranalyse

**Comment by IGLO70** [comment]
Anscheinend wurden die Bilder im E-Mail und die Anhänge nicht mit gesendet. Ich habe das jetzt auf einen Downloadserver gepackt. 

Download unter: https://we.tl/t-V489GHmWrf 

 

Mit besten Grüßen

 

Ignaz Lorenz

 

Von: Josef Spitzlberger <notifications@github.com> 
Gesendet: Sonntag, 17. Mai 2020 12:44
An: spitzlbergerj/CaravanPi <CaravanPi@noreply.github.com>
Cc: IGLO70 <ignaz.lorenz@gmail.com>; Mention <mention@noreply.github.com>
Betreff: Re: [spitzlbergerj/CaravanPi] Ich habe Probleme - Dateien fehlern (#2)

 

Hallo Ignaz,
ich kann hier die Meldungstexte nicht sehen. Daher tu ich mich schwer mit der Fehleranalyse

**Comment by spitzlbergerj** [comment]
Hallo Ignaz,

die Fehlermeldungen deuten darauf hin, dass der I2C Bus Fehler aufweist und davon nicht gelesen werden kann. Da kann ich leider nicht helfen. Bitte versuche den Bus zum Laufen zu bekommen. Dann sollten die Skripte auch funktionieren.

Viele Grüße

Josef Spitzlberger

Von: IGLO70 <notifications@github.com>
Gesendet: Sonntag, 17. Mai 2020 15:31
An: spitzlbergerj/CaravanPi <CaravanPi@noreply.github.com>
Cc: josef@spitzlberger.de; State change <state_change@noreply.github.com>
Betreff: Re: [spitzlbergerj/CaravanPi] Ich habe Probleme - Dateien fehlern (#2)

Anscheinend wurden die Bilder im E-Mail und die Anhänge nicht mit gesendet. Ich habe das jetzt auf einen Downloadserver gepackt.

Download unter: https://we.tl/t-V489GHmWrf



Mit besten Grüßen



Ignaz Lorenz



Von: Josef Spitzlberger <notifications@github.com>
Gesendet: Sonntag, 17. Mai 2020 12:44
An: spitzlbergerj/CaravanPi <CaravanPi@noreply.github.com>
Cc: IGLO70 <ignaz.lorenz@gmail.com>; Mention <mention@noreply.github.com>
Betreff: Re: [spitzlbergerj/CaravanPi] Ich habe Probleme - Dateien fehlern (#2)



Hallo Ignaz,
ich kann hier die Meldungstexte nicht sehen. Daher tu ich mich schwer mit der Fehleranalyse

**Comment by IGLO70** [comment]
Ich bin gerade dabei, das gesamte System auf einem neuen Pi 4 aufzusetzen. Der nicht funktionierende i2c Bus betrifft aber nur die Lageanzeige. Die Klimadaten sind aber in den Datendateien enthalten und kommen nicht vom i2c. Trotzdem werden Sie nicht angezeigt. Hier gibt es anscheinend Probleme beim Auslesen aus der Datei. Worin hier der Fehler besteht, verstehe ich nicht.

 

Gibt es hierfür eine Idee.

 

Mit besten Grüßen

 

Ignaz Lorenz

 

Von: Josef Spitzlberger <notifications@github.com> 
Gesendet: Sonntag, 17. Mai 2020 19:04
An: spitzlbergerj/CaravanPi <CaravanPi@noreply.github.com>
Cc: IGLO70 <ignaz.lorenz@gmail.com>; Mention <mention@noreply.github.com>
Betreff: Re: [spitzlbergerj/CaravanPi] Ich habe Probleme - Dateien fehlern (#2)

 

Hallo Ignaz, 

die Fehlermeldungen deuten darauf hin, dass der I2C Bus Fehler aufweist und davon nicht gelesen werden kann. Da kann ich leider nicht helfen. Bitte versuche den Bus zum Laufen zu bekommen. Dann sollten die Skripte auch funktionieren. 

Viele Grüße 

Josef Spitzlberger 

Von: IGLO70 <notifications@github.com <mailto:notifications@github.com> > 
Gesendet: Sonntag, 17. Mai 2020 15:31 
An: spitzlbergerj/CaravanPi <CaravanPi@noreply.github.com <mailto:CaravanPi@noreply.github.com> > 
Cc: josef@spitzlberger.de <mailto:josef@spitzlberger.de> ; State change <state_change@noreply.github.com <mailto:state_change@noreply.github.com> > 
Betreff: Re: [spitzlbergerj/CaravanPi] Ich habe Probleme - Dateien fehlern (#2) 

Anscheinend wurden die Bilder im E-Mail und die Anhänge nicht mit gesendet. Ich habe das jetzt auf einen Downloadserver gepackt. 

Download unter: https://we.tl/t-V489GHmWrf 



Mit besten Grüßen 



Ignaz Lorenz 



Von: Josef Spitzlberger <notifications@github.com <mailto:notifications@github.com> > 
Gesendet: Sonntag, 17. Mai 2020 12:44 
An: spitzlbergerj/CaravanPi <CaravanPi@noreply.github.com <mailto:CaravanPi@noreply.github.com> > 
Cc: IGLO70 <ignaz.lorenz@gmail.com <mailto:ignaz.lorenz@gmail.com> >; Mention <mention@noreply.github.com <mailto:mention@noreply.github.com> > 
Betreff: Re: [spitzlbergerj/CaravanPi] Ich habe Probleme - Dateien fehlern (#2) 



Hallo Ignaz, 
ich kann hier die Meldungstexte nicht sehen. Daher tu ich mich schwer mit der Fehleranalyse

**Comment by spitzlbergerj** [comment]
Hallo Ignaz,
ich baue den CaravanPi gerade noch einmal von Grund auf neu auf und mache die DOKU dazu auch in Deutsch. Schau einfach mal ins Wiki. Vielleicht kannst du da ja auch der Reihe nach mitmachen/mitbauen
Viele Grüße 
Sepp
